import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Techinnover Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center space-y-7 flex-col  w-full h-screen">
        <div className="text-3xl text-center font-bold">
          Techinnover(Test) Educational Platform
        </div>
        <div className="space-y-4 flex flex-col items-center">
          <Link href={'/login'}>
            <a className="px-6 inline-block text-center cursor-pointer hover:opacity-75 hover:scale-105 transition-all ease-in-out py-3 w-28 text-lg font-semibold bg-orange-600 text-white rounded-md">
              Login
            </a>
          </Link>
          <Link href="/sign-up">
            <a className="px-6 inline-block text-center cursor-pointer hover:opacity-75 hover:scale-105 transition-all ease-in-out w-28 py-3 text-lg font-semibold bg-blue-500 text-white rounded-md">
              Sign up
            </a>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Home;
